### ISSUE TITLE
Mask-RCNN-baseline results

### ISSUE THREAD

**Issue by lxtGH** [youtubevos/MaskTrackRCNN#10]
Hi! Thanks for share your codes and I have some question about your paper. In your paper, I didn't find per frame mask-rcnn baseline results? Is it in table 2 row 1??? (16.2 AP) or it is Mask-Track-RCNN baseline on this dataset?

**Comment by zack624** [comment]
According to the Evaluation Metrics, the IoU of one instance will be calculated across all the frames. So  it may not be able to implement only per frame. ?_?
