### ISSUE TITLE
mAP of MaskTrackRCNN tested on codalab server

### ISSUE THREAD

**Issue by Jiangfeng-Xiong** [youtubevos/MaskTrackRCNN#11]
I use the pretrained model epoch_12.pth from Google Drive, and then evaluate the results on the codalab server, but i got mAP: 0.248, however, it should be 0.3 as reported in the paper. Any suggestion? Thank you!

**Comment by Jiangfeng-Xiong** [comment]
And besides, when I load the model weights epoch_12.th, I got this message 
>unexpected key in source state_dict: track_head.fc.weight, track_head.fc.bias
> missing keys in source state_dict: track_head.fcs.1.bias, track_head.fcs.0.bias, track_head.fcs.0.weight, track_head.fcs.1.weight

**Comment by linjieyangsc** [comment]
@Jiangfeng-Xiong It seems you are using a wrong config file. Please make sure to use this file to load the model: `configs/masktrack_rcnn_r50_fpn_1x_youtubevos.py`

**Comment by Jiangfeng-Xiong** [comment]
<img width="1412" alt="屏幕快照 2019-07-31 上午10 09 36" src="https://user-images.githubusercontent.com/18069771/62178423-9abdf380-b37b-11e9-890b-ccb29731cac2.png"> @linjieyangsc

**Comment by ZENGXH** [comment]
@linjieyangsc  I also got 24.8..

**Comment by linjieyangsc** [comment]
@Jiangfeng-Xiong @ZENGXH It seems that the previous checkpoint was problematic. I have updated it with the correct one. Please try again and let me know if any questions. Sorry for the inconvenience.

**Comment by Jiangfeng-Xiong** [comment]
it works now, thank you @linjieyangsc

**Comment by voidtaoist** [comment]
I use the pretrained model epoch_12.pth from Google Drive, and then evaluate the results on the codalab server, but i got mAP: 0.301, however, it should be 0.303 as reported in the paper. Any suggestion? Thank you!
