### ISSUE TITLE
The evaluation serve and the baseline results.

### ISSUE THREAD

**Issue by irfanICMLL** [youtubevos/MaskTrackRCNN#21]
Hi, thank you for sharing this good benchmark task and the baseline code.
I have some questions when reproducing the baseline.
I can not find the information about the batch size in your paper.
You have mentioned that you use four GPU for training. Do you use 4*8 as the training batchsize?

I have trained a model using your default settings with one single GPU. Now I want to evaluate the results. However, the link https://competitions.codalab.org/competitions/23215 does not work.
I found a submit server here: https://competitions.codalab.org/competitions/20128#participate-submit_results
After running the test_video.py, I have got an output.pkl and an output.json.
It also prints the information like:
"Starting evaluate segm
Annotations does not exist"
Is it a normal one?
When I try to upload the json, the website gives a piece of error information "Invalid file type (application/json)."

Can you help me with this?

**Comment by li-yanling** [comment]
@irfanICMLL Hi, did you find out why it shows "invidalid file type (application/json)" when upload output.json? The same problem happens to me
