### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Glee1018** [youtubevos/MaskTrackRCNN#22]
As is showed below, my training ends with Segmentation fault, Could someone tell me why ？

(MaskTrackRCNN) [lijie@yq01-gpu-255-126-19-00 MaskTrackRCNN-master]$ python3 tools/train.py configs/masktrack_rcnn_r50_fpn_1x_youtubevos.py
2019-12-17 21:52:08,555 - INFO - Distributed training: False
2019-12-17 21:52:09,311 - INFO - load model from: modelzoo://resnet50
2019-12-17 21:52:09,625 - WARNING - unexpected key in source state_dict: fc.weight, fc.bias

missing keys in source state_dict: layer4.0.downsample.1.num_batches_tracked, layer3.4.bn2.num_batches_tracked, layer2.1.bn3.num_batches_tracked, layer1.0.bn1.num_batches_tracked, layer1.1.bn1.num_batches_tracked, layer2.3.bn1.num_batches_tracked, layer3.5.bn2.num_batches_tracked, layer2.0.bn3.num_batches_tracked, layer3.3.bn3.num_batches_tracked, layer3.2.bn3.num_batches_tracked, layer3.4.bn3.num_batches_tracked, layer2.2.bn1.num_batches_tracked, layer3.2.bn2.num_batches_tracked, layer3.1.bn2.num_batches_tracked, layer1.0.downsample.1.num_batches_tracked, bn1.num_batches_tracked, layer4.2.bn1.num_batches_tracked, layer2.1.bn1.num_batches_tracked, layer3.0.bn3.num_batches_tracked, layer1.2.bn3.num_batches_tracked, layer3.4.bn1.num_batches_tracked, layer1.0.bn2.num_batches_tracked, layer2.2.bn2.num_batches_tracked, layer2.0.bn1.num_batches_tracked, layer2.1.bn2.num_batches_tracked, layer4.0.bn2.num_batches_tracked, layer2.0.bn2.num_batches_tracked, layer3.5.bn3.num_batches_tracked, layer3.3.bn2.num_batches_tracked, layer1.0.bn3.num_batches_tracked, layer4.1.bn3.num_batches_tracked, layer3.1.bn1.num_batches_tracked, layer3.5.bn1.num_batches_tracked, layer1.1.bn2.num_batches_tracked, layer4.0.bn3.num_batches_tracked, layer3.3.bn1.num_batches_tracked, layer4.1.bn2.num_batches_tracked, layer2.3.bn2.num_batches_tracked, layer4.1.bn1.num_batches_tracked, layer2.3.bn3.num_batches_tracked, layer3.1.bn3.num_batches_tracked, layer2.0.downsample.1.num_batches_tracked, layer3.0.bn2.num_batches_tracked, layer4.2.bn2.num_batches_tracked, layer1.2.bn2.num_batches_tracked, layer4.0.bn1.num_batches_tracked, layer1.1.bn3.num_batches_tracked, layer3.2.bn1.num_batches_tracked, layer3.0.downsample.1.num_batches_tracked, layer2.2.bn3.num_batches_tracked, layer1.2.bn1.num_batches_tracked, layer3.0.bn1.num_batches_tracked, layer4.2.bn3.num_batches_tracked

loading annotations into memory...
Done (t=14.82s)
creating index...
index created!
2019-12-17 21:53:59,679 - INFO - load checkpoint from https://s3.ap-northeast-2.amazonaws.com/open-mmlab/mmdetection/models/mask_rcnn_r50_fpn_1x_20181010-069fa190.pth
2019-12-17 21:53:59,879 - WARNING - missing keys in source state_dict: track_head.fcs.0.bias, track_head.fcs.1.bias, track_head.fcs.1.weight, track_head.fcs.0.weight

2019-12-17 21:53:59,900 - INFO - Start running, host: lijie@yq01-gpu-255-126-19-00, work_dir: /home/lijie/MaskTrackRCNN-master/work_dirs/masktrack_rcnn_r50_fpn_1x_youtubevos
2019-12-17 21:53:59,900 - INFO - workflow: [('train', 1)], max: 12 epochs
Segmentation fault

**Comment by Glee1018** [comment]
gcc 4.9.2 is ok

**Comment by anirudh-chakravarthy** [comment]
Hi,

I am facing this same issue. Would you be kind enough to help me figure out the issue? Is it a GCC version issue? My current gcc version is 4.8.5.

**Comment by Glee1018** [comment]
Hi,
I'am very glad to get your email. Yes, it is a GCC version issue,&nbsp; and my code works well with gcc 4.9.2, 5.2 and 6.3, maybe you can try 4.9.2 or above.&nbsp;I hope you will soon solve this issue.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Anirudh S Chakravarthy"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月20日(星期三) 下午5:32
收件人:&nbsp;"youtubevos/MaskTrackRCNN"<MaskTrackRCNN@noreply.github.com&gt;;
抄送:&nbsp;"李杰"<869237287@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [youtubevos/MaskTrackRCNN] Segmentation fault (#22)





 
Hi,
 
I am facing this same issue. Would you be kind enough to help me figure out the issue? Is it a GCC version issue? My current gcc version is 4.8.5.

**Comment by anirudh-chakravarthy** [comment]
Hi, 

I was able to resolve it by rebuilding with a higher GCC version, and hence had deleted my comment. Thank you very much for your response!
