### ISSUE TITLE
Import YTVOS

### ISSUE THREAD

**Issue by trevor-taeyeop** [youtubevos/MaskTrackRCNN#33]
Hi, thank you for sharing good works.

I tried this command, but could not solved.
_pip install git+https://github.com/youtubevos/cocoapi.git#"egg=pycocotools&subdirectory=PythonAPI"_

**Could you advise how to handle this??**

> (MaskTrackRCNN) user@user:/sdata1/workspace/MaskTrackRCNN$ python3 tools/test_video.py configs/masktrack_rcnn_r50_fpn_1x_youtubevos.py models/epoch_12.pth --out output --eval segm
> Traceback (most recent call last):
>   File "tools/test_video.py", line 8, in <module>
>     from mmdet import datasets
>   File "/home/user/anaconda3/envs/MaskTrackRCNN/lib/python3.6/site-packages/mmdet/datasets/__init__.py", line 1, in <module>
>     from .custom import CustomDataset
>   File "/home/user/anaconda3/envs/MaskTrackRCNN/lib/python3.6/site-packages/mmdet/datasets/custom.py", line 11, in <module>
>     from .extra_aug import ExtraAugmentation
>   File "/home/user/anaconda3/envs/MaskTrackRCNN/lib/python3.6/site-packages/mmdet/datasets/extra_aug.py", line 5, in <module>
>     from mmdet.core.evaluation.bbox_overlaps import bbox_overlaps
>   File "/home/user/anaconda3/envs/MaskTrackRCNN/lib/python3.6/site-packages/mmdet/core/__init__.py", line 5, in <module>
>     from .evaluation import *  # noqa: F401, F403
>   File "/home/user/anaconda3/envs/MaskTrackRCNN/lib/python3.6/site-packages/mmdet/core/evaluation/__init__.py", line 4, in <module>
>     from .coco_utils import coco_eval, fast_eval_recall, results2json, results2json_videoseg, ytvos_eval
>   File "/home/user/anaconda3/envs/MaskTrackRCNN/lib/python3.6/site-packages/mmdet/core/evaluation/coco_utils.py", line 5, in <module>
>     from pycocotools.ytvos import YTVOS
> ModuleNotFoundError: No module named 'pycocotools.ytvos'
>

**Comment by anirudh-chakravarthy** [comment]
Hi, 

I was wondering if you were able to run evaluation? I ran the same command, however, I face this error. 

`ValueError: The output file must be a pkl file.`

It seems that your checkpoint file, too,  is a `.pth`. Did you face this issue? If so, how did you resolve this?

**Comment by ShellyLingling** [comment]
> Hi,
> 
> I was wondering if you were able to run evaluation? I ran the same command, however, I face this error.
> 
> `ValueError: The output file must be a pkl file.`
> 
> It seems that your checkpoint file, too, is a `.pth`. Did you face this issue? If so, how did you resolve this?

@anirudh-chakravarthy  Have you solved this problem?

**Comment by anirudh-chakravarthy** [comment]
Hi,

Yes, I was able to solve this issue. You should use the following format for running evaluation:
`python3 tools/test_video.py configs/masktrack_rcnn_r50_fpn_1x_youtubevos.py [MODEL_PATH] --out _results.pkl_ --eval segm`
