### ISSUE TITLE
Dataset organization

### ISSUE THREAD

**Issue by danperazzo** [youtubevos/MaskTrackRCNN#35]
Hello, thanks for releasing this work! I did not understand how to organize the dataset into the form that you exposed on the README.md. Could you please explain more?

**Comment by danperazzo** [comment]
And how should I go to see the segmentation result and not only the .json file?

**Comment by liz2020** [comment]
You can find the MSCOCO format explanation at [YouTubeVIS's website](https://competitions.codalab.org/competitions/20128#participate-get-data).

**Comment by danperazzo** [comment]
Ok, thank you!
