### ISSUE TITLE
ModuleNotFoundError: No module named 'pycocotools.ytvos'

### ISSUE THREAD

**Issue by lly2111101** [youtubevos/MaskTrackRCNN#4]
hi,when I run the command "python tools/train.py configs/masktrack_rcnn_r50_fpn_1x_youtubevos.py", it returned an error which was "ModuleNotFoundError: No module named 'pycocotools.ytvos'". It seems like the 'pycocotools.ytvos' is your modified and new added part. Could you please tell me how to solve it?

**Comment by linjieyangsc** [comment]
@lly2111101 you need to install our customized cocoapi at: https://github.com/youtubevos/cocoapi
