### ISSUE TITLE
About the evaluation in the codalab

### ISSUE THREAD

**Issue by hero-y** [youtubevos/MaskTrackRCNN#41]
Hi, when I try to upload the json file to the codalab( https://competitions.codalab.org/competitions/20128#participate-submit_results), the website gives a piece of error information "Invalid file type (application/json)." Is it normal? How can I evaluate the model? Thank you !

**Comment by liuwenran** [comment]
how to solve this problem? The validation set and test set has same video id, which start from 1, so how does the sever know the submission is for validation or for test.
