### ISSUE TITLE
ImportError: cannot import name 'parallel_test'

### ISSUE THREAD

**Issue by Dorothylyly** [youtubevos/MaskTrackRCNN#42]
when I use "python3 tools/test_video.py configs/masktrack_rcnn_r50_fpn_1x_youtubevos.py ./epoch_12.pth --out ./output --eval segm" to run the code. I got this error, but I have already installed 'mmcv' package.

I have no idea about this, could you please tell me what should I do?

**Comment by Dorothylyly** [comment]
the problem is :
 `Traceback (most recent call last):
  File "tools/test_video.py", line 5, in <module>
    from mmcv.runner import load_checkpoint, parallel_test, obj_from_dict
ImportError: cannot import name 'parallel_test'`

**Comment by Dorothylyly** [comment]
solved by installing mmcv == 0.2.0

**Comment by zhw2020913** [comment]
有0.2.0版本？
