### ISSUE TITLE
The pretained  weights of Mask R-CNN is not available. 

### ISSUE THREAD

**Issue by GT9505** [youtubevos/MaskTrackRCNN#50]
The [pretained  weights of Mask R-CNN](https://s3.ap-northeast-2.amazonaws.com/open-mmlab/mmdetection/models/mask_rcnn_r50_fpn_1x_20181010-069fa190.pth) is not available. 
Could you provide a link to download the weights.

**Comment by Haelles** [comment]
The [pretrained weight of Mask R-CNN](https://s3.ap-northeast-2.amazonaws.com/open-mmlab/mmdetection/models/mask_rcnn_r50_fpn_1x_20181010-069fa190.pth) can be downloaded  [here](https://open-mmlab.oss-cn-beijing.aliyuncs.com/mmdetection/models/mask_rcnn_r50_fpn_1x_20181010-069fa190.pth)
