### ISSUE TITLE
The baseline MAP can be achieved using the default setting?

### ISSUE THREAD

**Issue by jiujing23333** [youtubevos/MaskTrackRCNN#6]
Hi, Linjie.
under the default setting, I train a model using a single GPU. But it seems to be difficult to achieve 30.3 MAP. Besides, I note that the learning rate is 0.05 in your paper,  while 0.005 in your code?
Thanks

**Comment by linjieyangsc** [comment]
@jiujing23333 Thanks for pointing out. We use 0.005 as the initial learning rate and use 4 gpus for training. The result is kind of unstable for different trials in our current setting, which ranges from 0.28 to 0.31. I guess better data augmentation can improve this situation.

**Comment by jiujing23333** [comment]
@linjieyangsc Thanks, I will try it.

**Comment by Jiangfeng-Xiong** [comment]
@jiujing23333 have you got the baseline result on validation dataset？
