### ISSUE TITLE
Where does instances_train_sub.json locate

### ISSUE THREAD

**Issue by MaureenZOU** [youtubevos/MaskTrackRCNN#8]
we could only download train.json or meta.json, where can we find instances_train_sub.json?
It would be really appreciated if someone could give me some hint, Thanks ahead!

**Comment by linjieyangsc** [comment]
Hi, please check evaluation server for the video instance segmentation on this page:
https://youtube-vos.org/dataset/vis/
Thanks!

**Comment by linjieyangsc** [comment]
@MaureenZOU Actually the train.json is the one we use as instances_train_sub.json in our code. Sorry for the misunderstanding.

**Comment by MaureenZOU** [comment]
Thanks so much, got it. I will close this issue : _)
